### ISSUE TITLE
App not work in 9.0

### ISSUE THREAD

**Issue by Daud-Ahmad** [egcodes/speed-test#10]
This app not working in 9.0 android version. resolve the issue and update

**Comment by almaddy95** [comment]
> This app not working in 9.0 android version. resolve the issue and update

I think they're still working on it and the update is still in progress. It will available soon as there are not so many apps that compatible yet. In the meantime, if you yourself are an android apps developer, I guess you can make contributions on this project to increase more progress on the update. No offence, it just my opinion though.

**Comment by ayoubcheh** [comment]
> 
> 
> This app not working in 9.0 android version. resolve the issue and update

Hi same error if you update this code help me

**Comment by egcodes** [comment]
Bug fixed. Maybe ping may not work properly. But download and upload is working.
