### ISSUE TITLE
java.net.ConnectException: Failed to connect to speedtest

### ISSUE THREAD

**Issue by sam3961** [egcodes/speed-test#12]
I am running this app in android 10. Ping is working fine but getting error on download and upload with the below exception.

**java.net.ConnectException: Failed to connect to speedtest.sonepat.softechinfosol.com/64:ff9b::cb4c:f9da:443**

**Comment by egcodes** [comment]
An error caused by the servers of the nearest speedtest test center. Maybe it can be tried by adding code that will ignore this test center in the code.

**Comment by CholoNaraval** [comment]
how did u fix ping issue?
