### ISSUE TITLE
ChartFactory doesn't exist

### ISSUE THREAD

**Issue by lilou115** [egcodes/speed-test#3]
Hello, i'm trying to implement the code, when i import import org.achartengine.ChartFactory; it says "Cannot resolve symbol ChartFactory", can someone help me with this please?

**Comment by egcodes** [comment]
Have you tried to build it? Already added as dependency.

![image](https://user-images.githubusercontent.com/3457067/49524146-40d45f00-f8bc-11e8-8d51-aa6ab11616cf.png)

**Comment by tonycode** [comment]
Got same bug

However, `achartengine` now doesn't contain `org.achartengine.ChartFactory` class. Seems like it was in earlier snapshot version of the library and now it is removed

**Comment by dgaurav-163** [comment]
Getting same problem.. Any solution for this??

**Comment by egcodes** [comment]
achartengine dependency was solved by adding a manual
