### ISSUE TITLE
Crashing at "Begin Speed Test"

### ISSUE THREAD

**Issue by swapnikap** [egcodes/speed-test#4]
App is crashing with NullPointerException.
App worked perfectly a few days before. But now crashing in all the devices. 

    Process: egcodes.com.speedtest, PID: 14283
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at egcodes.com.speedtest.MainActivity$1$1.run(MainActivity.java:239)
        at java.lang.Thread.run(Thread.java:818)

**Comment by egcodes** [comment]
Speedtest config http (unsecure) url has disabled. It collapsed because of it. I fixed the code. The application will be uploaded to the Play Store for a few days. Thanks
