### ISSUE TITLE
Cannot retrieve speedtest configuration

### ISSUE THREAD

**Issue by kathirrohlig** [egcodes/speed-test#5]
I am doing the speed test from my firewall, it able to reach the git hub and got http request response but when retrieve the speedtest configuration it got failed.. what would be the issue?

this problem more then 1 week. Looks like global issue.
![zippp](https://user-images.githubusercontent.com/47314787/52196153-bb9c0500-2880-11e9-9be0-96a4d58df8a3.PNG)

**Comment by egcodes** [comment]
Speedtest config http (unsecure) url has disabled. It collapsed because of it. I fixed the code. The application will be uploaded to the Play Store for a few days. Thanks
