### ISSUE TITLE
Wrong speed counts when used as a fragment? 

### ISSUE THREAD

**Issue by kesenls** [egcodes/speed-test#7]
I got a rather strange issue 

While your code works great as is 
if i try to implement it as a fragment on my project i get lower speed readings :/
any idea ?

thanks in advance

**Comment by AnserBaby** [comment]
i use china mobile network too

**Comment by egcodes** [comment]
> I got a rather strange issue
> 
> While your code works great as is
> if i try to implement it as a fragment on my project i get lower speed readings :/
> any idea ?
> 
> thanks in advance

Do you still having the problem ?
