### ISSUE TITLE
this app doesn't work 

### ISSUE THREAD

**Issue by julia-arch** [egcodes/speed-test#9]
Hi, I try this code and it's compiled without any error in Android Studio but this application doesn't work for me , please can you help me

**Comment by GandhiMilind** [comment]
I know It's late, But may i know on Which android version are you running this code?

**Comment by Daud-Ahmad** [comment]
this app not working in android 9.0 version. after ping test it stopped. it not test download speed. please tell me any solution??

**Comment by egcodes** [comment]
Bug fixed. Maybe ping may not work properly. But download and upload is working.
